package main

import (
	"fmt"
	"kursach/lib"
)

func main() {
	data := lib.Parse("test.json")
	e := lib.CalculateE(data)
	sd := lib.CalculateStandardDeviation(data, e)
	diff := lib.CalculateDifferenceESD(e, sd)
	sum := lib.CalculateSumESD(e, sd)
	a := lib.CalculateA(e, sd)
	b := lib.CalculateB(a, e)
	// fmt.Println(e)
	fmt.Printf("data: %v\n", data)
	fmt.Println()
	fmt.Printf("E: %v\n", e)
	fmt.Println()
	fmt.Printf("SD: %v\n", sd)
	fmt.Println()
	fmt.Printf("Difference: %v\n", diff)
	fmt.Println()
	fmt.Printf("Sum: %v\n", lib.CalculateSumESD(e, sd))
	fmt.Println()
	fmt.Printf("O1: %v\n", lib.CalculateO1(data, diff))
	fmt.Println()
	fmt.Printf("O2: %v\n", lib.CalculateO2(data, diff, e))
	fmt.Println()
	fmt.Printf("O3: %v\n", lib.CalculateO3(data, sum, e))
	fmt.Println()
	fmt.Printf("O4: %v\n", lib.CalculateO4(data, sum))
	fmt.Println()
	fmt.Printf("X2: %v\n", lib.CalculateX2(lib.CalculateO1(data, diff), lib.CalculateO2(data, diff, e), lib.CalculateO3(data, sum, e), lib.CalculateO4(data, sum)))
	fmt.Println()
	fmt.Printf("P: %v\n", lib.ChiSquareRightTailProbability(lib.CalculateX2(lib.CalculateO1(data, diff), lib.CalculateO2(data, diff, e), lib.CalculateO3(data, sum, e), lib.CalculateO4(data, sum)), 1))
	fmt.Println()
	fmt.Printf("A: %v\n", lib.CalculateA(e, sd))
	fmt.Println()
	fmt.Printf("B: %v\n", lib.CalculateB(lib.CalculateA(e, sd), e))
	fmt.Println()
	fmt.Printf("Uniform O1: %v\n", lib.UniO1(data, lib.CalculateA(e, sd)))
	fmt.Println()
	fmt.Printf("Uniform O2: %v\n", lib.UniO2(data, lib.CalculateA(e, sd), e))
	fmt.Println()
	fmt.Printf("Uniform O3: %v\n", lib.UniO3(data, lib.CalculateB(lib.CalculateA(e, sd), e), e))
	fmt.Println()
	fmt.Printf("Uniform O4: %v\n", lib.UniO4(data, b))

}
